<?php
/**
 * Created by IntelliJ IDEA.
 * User: charlespretzer
 * Date: 11/20/17
 * Time: 18:47
 */

namespace AppBundle\Services;


class PhotoUploaderMockTest extends PhotoUploader {

    public function __construct() {
    }

    public function getUploaderPath() {
        return parent::getUploaderPath(); // TODO: Change the autogenerated stub
    }


}