name: pages
resolver:
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 1s
root: /ingenious-pages/web
services:
  album-manager:
    server: 'marathon.mesos'
    service: 'service=_album-manager._tcp'
    expose_external: true
    healthcheck: true
    oss_port: 12001
  content-service:
    server: 'marathon.mesos'
    service: 'service=_content-service._tcp'
    expose_external: true
    healthcheck: true
    oss_port: 12002
  uploader:
    server: 'marathon.mesos'
    service: 'service=_uploader._tcp'
    expose_external: true
    healthcheck: true
    oss_port: 12006
  user-manager:
    server: 'marathon.mesos'
    service: 'service=_user-manager._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
    oss_port: 12007
