name: pages
resolver:
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 1s
root: /ingenious-pages/web
services:
  album-manager:
    server: 'marathon.mesos service=_album-manager._tcp'
    expose_external: true
    healthcheck: true
  content-service:
      server: 'marathon.mesos service=_content-service._tcp'
      expose_external: true
      healthcheck: true
  uploader:
    server: 'marathon.mesos service=_uploader._tcp'
    expose_external: true
    healthcheck: true
  user-manager:
    server: 'marathon.mesos service=_user-manager._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
